import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import style from '../styles/Main.module.css' 
import Descargarbutton from '../../components/Descargarbutton'; 

import Image from 'next/image';
const inter = Inter({ subsets: ['latin'] })



export default function Home() {

  const imageName = '/invitacion.jpg';


  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className={style.video_container}> 
          <video controls className={style.video_origin}>
            <source src='rubius_invitacion.mp4' type='video/mp4'/>
          </video>
        </div>

        <div className={style.informacion_container}>
          {/* <h1>JULIAN Y RENATA</h1>
          <h2>BIENVENIDO A NUESTRA BODA</h2>
          <h2>CONFIRMA TU ASISTENCIA</h2> */}
          <a className={style.button_confirmacion} href='https://wa.link/v5ott5'>CONFIRMAR</a> 
          <a href="https://www.google.com.ar/maps/place/Catedral+Metropolitana+de+Buenos+Aires/@-34.6075694,-58.3732574,17z/data=!3m1!4b1!4m6!3m5!1s0x95bcb9c134355bc3:0xe7611c1602820d34!8m2!3d-34.6075694!4d-58.3732574!16zL20vMGR0dGs1?hl=es&authuser=0">¿COMO LLEGAR?</a>
        </div>

        {/* <div className={style.temporizador_container}>
          <h2>238d : 48h : 34min</h2>
        </div> */}

        


       {/* <Link href="./Formulario">
          Contactame
        </Link> */}
      

        

        
      </main>
    </>
  )
}
